<!DOCTYPE html>
            <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <base href="<?php echo BASE_URL ?>">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
                    <title>TPE-Tudai</title>
                </head>
                <body>
                    <header>
                        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                            <a class="navbar-brand" href="homeInvitado">Home</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarText">
                                <ul class="navbar-nav mr-auto">
                                    <?php if (!isset($_SESSION['USER_NOMBRE'])) : ?>
                                    <li class="nav-item active">
                                        <a class="nav-link" href="login"><i class="bi bi-arrow-90deg-left"></i> Ingresar</a>
                                    </li>
                                    <?php else : ?>
                                    <li class="nav-item">
                                        <a class="nav-link" href="logout">Salir</a>
                                    </li>
                                    <?php endif ?> 
                                </ul>
                            </div>
                        </nav>
                    </header>
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
                </body>
            </html>