<!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="UTF-8">
                <base href="<?php echo BASE_URL ?>">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
                <title>INGRESO - TPE</title>
            </head>
            <body>
                <div class="card">
                    <div class="card-header">
                        Ingreso
                    </div>
                    <div class="card-body">
                        <form action="Autenticar" method="post">
                            <div class="form-group">
                                <label for="formGroupExampleInput">Usuario</label>
                                <!--USUARIO: user -->
                                <input type="text" name="user" class="form-control" id="formGroupExampleInput" placeholder="Example input">
                            </div>
                            <div class="form-group">
                                <label for="formGroupExampleInput2">Contraseña</label>
                                <!--PASSWORD: admin -->
                                <input type="text" name="pass" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Ingresar">
                        
            
                            </div>
                        </form>
                    </div>
                </div>
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
            </body>
        </html>
    