<?php
require_once './Templates/header.phtml';  
?>
<main>
        <div class="d-flex flex-row">
            <div class="card ms-4 my-4">
                <div class="card-header">
                    Agregar escritor
                </div>
                <div class="card-body">
                    <form action="agregar" method="post">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Nombre del escritor</label>
                            <input type="text" name="nombreEscritor" class="form-control" id="formGroupExampleInput" placeholder="Nombre de Escritor ">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Profesion del escritor</label>
                            <input type="text" name="ProfesionEscritor" class="form-control" id="formGroupExampleInput" placeholder="Profesion Escritor">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Fecha de nacimiento del escritor</label>
                            <input type="date" name="FechaEscritor" class="form-control" id="formGroupExampleInput" placeholder="Fecha de Nacimiento Escritor">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="ingresar">
                        </div>
                    </form>
                </div>
            </div>
            <div class="card ms-4 my-4">
                <div class="card-header">
                    Ingrese libro
                </div>
                <div class="card-body">
                    <form action="agregarLibro" method="post">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese titulo</label>
                            <input type="text" name="titulo" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Titulo">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese genero</label>
                            <input type="text" name="genero" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Genero">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Seleccione autor</label>
                            <select name="autor" class="form-control" id="exampleFormControlSelect1">
                            <?php $autores = $Autores;
                            foreach($autores as $autor){
                            ?>
                            <option value="<?php echo $autor->Autor_id ?>"><?php echo $autor->Nombre_Autor ?></option>
                            <?php
                            }
                            ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Breve descripcion del libro</label>
                            <textarea name="descripcion" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="ingresar">
                        </div>
                    </form>
                </div>
            </div>
            <div class="card ms-4 my-4">
                <div class="card-header">
                    Actualizar datos de libro
                </div>
                <div class="card-body">
                    <form action="actualizar" method="post">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese titulo</label>
                            <input type="text" name="titulo" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Titulo">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese genero</label>
                            <input type="text" name="genero" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Genero">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese idLibro</label>
                            <input type="text" name="idLibro" class="form-control" id="formGroupExampleInput" placeholder="Ingrese id Libro">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Seleccione autor</label>
                            <select name="autor" class="form-control" id="exampleFormControlSelect1">
                            <?php $autores = $Autores;
                            foreach($autores as $autor){
                            ?>
                            <option value="<?php echo $autor->Autor_id ?>"><?php echo $autor->Nombre_Autor ?></option>
                            <?php
                            }
                            ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Breve descripcion del libro</label>
                            <textarea name="descripcion" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="ingresar">
                        </div>
                    </form>
                </div>
            </div>
            <div class="card ms-4 my-4">
                <div class="card-header">
                    Actualizar Autor
                </div>
                <div class="card-body">
                    <form action="actualizarAutor" method="post">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese idAutor</label>
                            <input type="text" name="Autor_id" class="form-control" id="formGroupExampleInput" placeholder="Ingrese id del Autor">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese Nombre</label>
                            <input type="text" name="Nombre" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Nombre">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese Profesion</label>
                            <input type="text" name="Profesion" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Profesion">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Ingrese Fecha de nacimiento</label>
                            <input type="date" name="Fecha" class="form-control" id="formGroupExampleInput" placeholder="Ingrese Fecha de Nacimiento">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="ingresar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="d-flex flex-row justify-content- flex-wrap">
            <?php $datos = $Cartas;
            foreach($datos as $dato){
            ?>
            <div class="card m-1" style="width: 15rem; ">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $dato->Titulo?></h5>
                    <h6 class="card-title"><?php 
                    $autores = $Autores;
                    foreach($autores as $autor){
                        if($autor->Autor_id == $dato->Autor_id){
                                echo $autor->Nombre_Autor;
                        }
                    }
                    ?>
                    </h6>
                    <p class="card-text"><?php echo $dato->Descripcion ?></p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><?php echo $dato->Genero?></li>
                    <li class="list-group-item">ID del libro: <?php echo $dato->Libro_id ?></li>
                </ul>
                <div class="card-body">
                    <a href="delete/<?php echo $dato->Libro_id ?>" class="card-link">Eliminar</a>
                    <a href="verMas/<?php echo $dato->Libro_id ?>" class="card-link">Ver mas</a>
                </div>
            </div>
            <?php 
            }
            ?>
       </div>
       <div>
                <ul class="list-group">
                    
                    <?php $autores = $Autores;
                   
                        foreach($Autores as $autor): ?>
                        <div class="container-fluid">
                            <li class="list-group-item active" aria-current="true">AUTOR</li>
                            <li class="list-group-item">Nombre: <?= $autor->Nombre_Autor ?></li>
                            <li class="list-group-item">Profesion: <?= $autor->Profesion_Autor ?></li>
                            <li class="list-group-item">Fecha de Nacimiento: <?= $autor->Fecha_Autor ?></li>
                        </div>
                        <div class="mx-auto" style="width: 200px;"> 
                            <a href="deleteAutor/<?php echo $autor->Autor_id ?>" class="card-link">
                               <button type="button" class="btn btn-dark" >Eliminar</button>
                            </a>
                        </div>
                    <?php endforeach ?>
                    
                </ul>
       </div>
       
</main>